global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus_scrape'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'SpringBootApplication'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['localhost:8081']
  - job_name: 'node_exporter_testing'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']